FROM ft-rails:on-build

EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]




# ------------------------------------------------------------------------------
# CMD is the command the container executes by default when you launch the built image. 
#
# How to build it:
# 		<< docker build -t ex02 . >>
#
# How to check it:
# 		<< docker run -it --rm -p 3000:3000 ex02 >>
# ------------------------------------------------------------------------------